version: "3.1"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5671:5671
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root

    networks:
      - backend

networks:
  backend: